name: recquest_21
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  awesome_notifications: ^0.7.4+1
  basic_utils: ^5.4.2
  cached_network_image: ^3.2.3
  camera: ^0.10.3
  connectivity_plus: ^3.0.3
  cool_alert: ^1.1.0
  date_time_picker: ^2.1.0
  dio: ^4.0.6
  fast_contacts: ^3.0.3
  file_manager: ^1.0.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter: 
    sdk: flutter
  fluttercontactpicker: ^4.7.0
  flutter_facebook_auth: ^5.0.7
  flutter_login_facebook: ^1.7.0
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  fl_location: ^1.2.2
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.4.1
  gallery_saver: ^2.3.2
  get: ^4.6.5
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.3
  google_maps_place_picker_mb: ^2.0.0-mb.20
  google_sign_in: ^5.0.7
  image_picker: ^0.8.6+3
  intl: ^0.17.0
  json_annotation: ^4.8.0
  json_serializable: any
  location: ^4.4.0
  map_launcher: ^2.2.3
  path: ^1.8.2
  path_provider: ^2.0.12
  permission_handler: ^10.2.0
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  # sms_autofill: ^2.0.0
  url_launcher: ^6.1.8
  workmanager: ^0.5.1
  geocoding: ^2.0.5
  contacts_service: ^0.6.3
  provider: ^6.0.5
  flutter_map: ^3.1.0
  place_picker: ^0.10.0
  share: ^2.0.4
  flutter_geocoder: ^0.2.2-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/locations.json
  fonts: 
    - family: Noto Sans
      fonts: 
        - asset: assets/fonts/NotoSansBold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansMedium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansRegular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansSemiBold.ttf
          weight: 600
